version: '3.8'

services:
    jenkins_service:
        build: .
        container_name: jenkins_deneme
        restart: always
        ports:
            - "1003:1003"
        environment:
          TZ: "Europe/Istanbul"
